#!/usr/bin/env python3
"""Build main-fold monthly carbon bounds from a prepared global_state.h5.

Run after build_global_state.py. Event targets come from a separate,
source-resolved input and are not generated by this script.
"""

import argparse
import json
from pathlib import Path

import h5py
import numpy as np


TARGET_NAMES = [
    'carbon_transition_fraction_lower', 'carbon_transition_fraction_upper',
    'carbon_sink_to_source_fraction_lower', 'carbon_sink_to_source_fraction_upper',
    'carbon_source_to_sink_fraction_lower', 'carbon_source_to_sink_fraction_upper',
    'carbon_known_support_fraction',
]


def build(root):
    folder = root / 'folds' / 'main'
    manifest = json.loads((folder / 'manifest.json').read_text())
    train_end = int(manifest['splits']['train'][1])
    with h5py.File(root / 'global_state.h5') as state:
        time = state['time'][:]
        state_valid = state['state_valid'][:].astype(bool)
        flux_valid = state['fgco2_valid'][:].astype(bool)
        comparable = state['transition_valid'][:].astype(bool)
        transition = state['sign_transition'][:]
        area = state['cell_area_km2'][:]
    joint = state_valid & flux_valid
    support = joint[:train_end].mean(0) >= .95
    weight = area * support
    denominator = weight.sum()
    if denominator <= 0:
        raise ValueError('Global carbon support is empty')
    columns = []
    for active in (transition != 0, transition == 1, transition == -1):
        confirmed = active & comparable
        columns.extend(((confirmed * weight).sum((1, 2)) / denominator,
                        ((confirmed | ~comparable) * weight).sum((1, 2)) / denominator))
    columns.append((comparable * weight).sum((1, 2)) / denominator)
    values = np.column_stack(columns).astype('float32')
    if not np.isfinite(values).all() or not ((values >= 0) & (values <= 1)).all():
        raise ValueError('Carbon fractions must be finite unit intervals')
    if not np.all(values[:, [0, 2, 4]] <= values[:, [1, 3, 5]]):
        raise ValueError('Carbon lower bounds exceed upper bounds')
    with h5py.File(folder / 'carbon_monthly.h5', 'x') as output:
        output['values'] = values
        output['valid'] = np.ones(values.shape, bool)
        output['time'] = time
        output['support'] = support
        output['area_weights_km2'] = weight
        output.attrs['target_names'] = json.dumps(TARGET_NAMES)
        output.attrs['definition'] = ('native adjacent 2-degree cell flux sign transitions; fractions of '
                                      'fold-admitted grid-cell area, not independent event counts')
        output.attrs['support'] = 'joint flux/state validity >=95% in this fold training months; outside support excluded'
        output.attrs['time_support'] = 'current and previous month only'
        output.attrs['encoder_visible'] = False
    print(json.dumps({'output': str(folder / 'carbon_monthly.h5'), 'support_cells': int(support.sum())}))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--root', type=Path, required=True)
    args = parser.parse_args()
    build(args.root)


if __name__ == '__main__':
    main()
